### ISSUE TITLE
cannot install: font dependencies fail

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-upload-validate#28]
When I try to `npm install mapbox-upload-validate`, I get:

```
npm ERR! fetch failed https://mapbox-npm.s3.amazonaws.com/package/mapbox-studio-default-fonts-0.0.4-4afb5235f457bd1c1a5a70fce6c2aa83bf7a851e.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
npm ERR! fetch failed https://mapbox-npm.s3.amazonaws.com/package/mapbox-studio-pro-fonts-1.0.0-9870a90b713f307b9391829602f4d5857e419615.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
```

npm version: 2.8.3

**Comment by rclark** [comment]
Hi @anandthakker -- I can't reproduce this problem on npm 2.8.3 or on 2.7.x versions. Could this have been a networking issue? These font dependencies are relatively large tarballs...

Anything else about your environment that you think might make a difference?

**Comment by anandthakker** [comment]
@rclark Hmm, not sure.  I've tried a few times in the past few days, and it's happened every time.   Every time from the garage, where i haven't been experiencing any other network issues.  I'll keep poking around and let you know.

**Comment by anandthakker** [comment]
Okay, I think it was an npm bug:  it looks like npm was sending an authentication header (used, e.g., for publishing), and amazon was rejecting the request as a result.  Removing my .npmrc file did the trick... but I wonder why this isn't happening to you (or anyone else I've asked).

**Comment by BergWerkGIS** [comment]
@anandthakker @rclark 

FYI: same thing just happened to me after I published a package via `npm publish`.

I did [`npm logout`](https://docs.npmjs.com/cli/logout) and now it works.
