### ISSUE TITLE
Don't end on the first tile that exceeds maximum

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-upload-validate#31]
1. I use Mapbox Studio to tile out a big shapefile, defaults of z0-11
2. Upload completes, comes back with `Tile exceeds maximum size of 500k at z0.`
3. I change the zoom range to z2-11
4. Upload completes, comes back with `Tile exceeds maximum size of 500k at z2.`

This error message needs improvement.

**Comment by rclark** [comment]
Most of these checks try to fail files fast, ideally without peeking at every single tile that may be included. What about exposing this as a `fail-fast` option of sorts, and otherwise inspecting the entire file? 

Would adjusting the error message so that it doesn't lead you towards just dropping a zoom level help here?

```
Maximum individual tile size of 500k exceeded
```

**Comment by tmcw** [comment]
The root question is whether this enables a good feedback loop. Right now it doesn't, because it says "if you drop a zoom level, it'll work" - when that actually isn't true.

If the tile size limit _is_ strongly influenced by zoom levels, and adjusting zoom bounds is what we want to endorse to fix it, then an ideal message would be something like

```
Tiles exceeds maximum size of 500k at z0-4. Adjust your zoom bounds to 4-20.
```

I suspect we'd be able to do this by iterating through each zoom level and running the same query for tiles only in that zoom. Looking at the query now, it doesn't seem like this would be significantly different performance-wise, since 

```
SELECT COUNT(1) AS count, MAX(LENGTH(tile_data)) AS size, zoom_level as z FROM tiles
```

Will iterate through all tiles in the database anyway

**Comment by hoogw** [comment]
I have the same error message, exceed 500kb limit. Here is why:

[https://www.mapbox.com/help/source-manual/](url)

Size limits

To ensure vector tiles rendering is fast, the following limits on source uploads are in place:

Individual vector tiles can not exceed 500kb at any zoom level
An entire .mbtiles export can not exceed 5gb

**Comment by hoogw** [comment]
[https://www.mapbox.com/help/upload-troubleshooting/](url)


Vector tileset limits in Mapbox Studio

MBTiles must be less than 5GB
KML, GPX, GeoJSON, and zipped Shapefiles must be less than 260MB
CSV files must be less than 5MB
TIFF and GeoTIFF files must be less than 10GB
Vector tileset limits in Mapbox Studio Classic

Up to 5GB of transfers are permitted at a time
Individual tiles must be less than 100kb
Individual tiles must be render-able into PNGs in one second (1000ms) or less
Average rendered tile must be less than 50kb
Average rendering time must be less than 300ms
Other Mapbox Studio Classic upload limits include:

Unzipped project.xml must be less than 750kb
Unzipped size should not exceed 5MB
Zipped .tm2z file must be under 500kb
Other file limits

When uploading to your account:

MBTiles: Maximum tile size is 512kB.
TIFF: Maximum file size is 10GB.
CSV: Maximum file size is 5MB.

**Comment by rclark** [comment]
> If the tile size limit is strongly influenced by zoom levels, and adjusting zoom bounds is what we want to endorse to fix it

I'm not sure whether this is what I'd like to endorse. The truth of the matter is, adjusting your zoom ranges _might_ help, but it also might not. This is why I'm leaning in the direction of a more succinct error message + perhaps more documentation on the pages @hoogw has linked?

Aside: the SQL @tmcw points out is nice for mbtiles files, where vector tiles are preconstructed, and the concept [could extend to serialtiles](https://github.com/mapbox/mapbox-upload-validate/blob/9f158737e5c63a03dbad2b4aeece8d8e82f5878a/lib/validators/serialtiles.js#L77-L112) (which studio classic uses). However, for other upload types we don't have tiles pre-built during the `mapbox-upload-validate` process, though our servers will return the same size error if encountered while it is generating tiles.

**Comment by tmcw** [comment]
No longer a priority; classic is deprecated.
