### ISSUE TITLE
Centralize & expose constants

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-upload-validate#32]
Instead of #11 the thing that browser-facing applications would benefit from would be something like

```
var uploadLimits = require('mapbox-upload-validate/limits');

uploadLimits.upload // 260MB
uploadLimits.tiffUpload // 10GB
```

Basically exposing _just the constants_ that define what the max file sizes are. Usecase is to pre-emptively warn & fail when a user is about to upload a too-large file.

**Comment by yhahn** [comment]
:+1: Let's split these out into a separate module anyway. For this use case big deps like

https://github.com/mapbox/mapbox-upload-validate/blob/master/package.json#L25-L26

will be painful even if they don't get bundled.

Next action: new module `mapbox-upload-limits` ?

**Comment by tmcw** [comment]
Yep, let's go with a separate module

**Comment by tmcw** [comment]
Creating mapbox-upload-limits now.
