### ISSUE TITLE
CSVs with spaces before lat and lon column names fail

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-upload-validate#56]
The validator fails on CSV files with spaces before their lat and lon heading column names. This only seems to happen when there are spaces before **both** the lat and lon heading names. If either lat or lon do not have spaces, the file is successfully validated. 

### To reproduce: 

Run mapbox-upload-validate on: 

```
id,timestamp,speed, latitude, longitude,mode
400251832,1453752801,-1.000000,38.906050,-77.048530,4
400251832,1453752887,-1.000000,38.906050,-77.048530,4
400251832,1453752501,-1.000000,38.906330,-77.048530,4
```

The following passes validation: 

```
id, timestamp, speed,latitude, longitude, mode
...
```

cc: @lyzidiamond

**Comment by danswick** [comment]
Bumping this. Saw another issue come through HelpScout today.

**Comment by tmcw** [comment]
Looks like [mapnik allows this](https://github.com/mapnik/mapnik/blob/7931295d3322b7cc57f820d7e2db6449d791159f/plugins/input/csv/csv_utils.cpp#L154) - it uses `.find` to see if there's a latitude/longitude string. So [detect-geocsv](https://github.com/mapbox/detect-geocsv/blob/master/detect-geocsv.js) could use String.trim to do the same thing.

**Comment by tmcw** [comment]
3.5.2 is published, with `unpacker`'s semver, it'll be included the next time anyone deploys unpacker.

**Comment by GretaCB** [comment]
Fixed, published and deployed 👍  Closing.
