### ISSUE TITLE
Handle SQLITE error: no such column: tile_data

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mapbox-upload-validate#65]
`SQLITE error: no such column: tile_data` is an error case that mapbox-upload-validate currently doesn't handle and should. 

- [x] Create a mbtiles test fixture with missing `tile_data` column
- [ ] Add error to the [mbtiles validator](https://github.com/mapbox/mapbox-upload-validate/blob/master/lib/validators/mbtiles.js#L22-L29)
- [ ] Add [a test](https://github.com/mapbox/mapbox-upload-validate/blob/master/test/validators.mbtiles.test.js) for this error, using the new text fixture

**Comment by who8mycakes** [comment]
This is fixed! 🎉  Closing.
