### ISSUE TITLE
Limit to patch bump for new GDAL dependency

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mapbox-upload-validate#70]
Noticed mapbox-upload-validate now [uses `gdal` as a dependency](https://github.com/mapbox/mapbox-upload-validate/blob/master/package.json#L25) for the new KML validation ( :tada: ).

Per [Node/Cpp versioning convention](https://github.com/mapbox/versioning-node-cpp), should gdal automatically update for minor or patch bumps? Thinking we might want to limit it to bump for patch updates, using a tilde `~` to avoid gdal being out of sync with other modules and to limit larger gdal changes not explicitly added by us.

cc @mapbox/unpacker

**Comment by mapsam** [comment]
Whoops - yes let's do this ASAP. Great catch @gretacb

**Comment by who8mycakes** [comment]
The gdal depedency has been updated in mapbox-upload-validate with the addition of kml validation tests. The commit is here: https://github.com/mapbox/mapbox-upload-validate/pull/72/commits/eebe303c6e68ff92552ef7b8a764f17df95a63a2, and the package.json now reflects: `"gdal": "~0.9.3",`
